language:
  - cpp

sudo: false

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

branches:
  only:
    - master
    - dev

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9

install:
  - pip install --user lutin

before_script:
  - cd ..
  - git clone https://github.com/generic-library/gtest-lutin.git --recurse-submodules
  - git clone https://github.com/generic-library/speex-dsp-lutin.git --recurse-submodules
  - git clone https://github.com/generic-library/z-lutin.git --recurse-submodules
  - git clone https://github.com/atria-soft/etk.git
  - git clone https://github.com/atria-soft/ejson.git
  - git clone https://github.com/musicdsp/audio.git
  - git clone https://github.com/musicdsp/audio-algo-drain.git
  - pwd
  - ls -l
  - if [ "$CXX" == "clang++" ]; then BUILDER=clang; else BUILDER=gcc; fi
  - if [ "$CXX" == "g++" ]; then COMPILATOR_OPTION="--compilator-version=4.9"; else COMPILATOR_OPTION=""; fi

script:
  - lutin -C -P -c$BUILDER $COMPILATOR_OPTION -mdebug -p audio-drain-test
  - ./out/Linux_x86_64/debug/staging/$BUILDER/audio-drain-test/usr/bin/audio-drain-test -l6

notifications:
  email:
    - yui.heero@gmail.com

